
import { jsPDF } from 'jspdf';
import { Document, Packer, Paragraph, TextRun, HeadingLevel, Table, TableRow, TableCell, BorderStyle } from 'docx';

export const exportToText = (meeting) => {
  let text = `MEETING TRANSCRIPT\n`;
  text += `Title: ${meeting.title}\n`;
  text += `Date: ${new Date(meeting.created_at || meeting.date).toLocaleDateString()}\n`;
  text += `Duration: ${meeting.duration || 'N/A'}\n\n`;

  text += `SUMMARY\n`;
  text += `Overview: ${meeting.summary?.overview || 'N/A'}\n\n`;
  
  if (meeting.summary?.keyPoints?.length) {
    text += `Key Points:\n`;
    meeting.summary.keyPoints.forEach(p => text += `- ${p}\n`);
    text += `\n`;
  }

  if (meeting.actionItems?.length) {
    text += `ACTION ITEMS\n`;
    meeting.actionItems.forEach(item => {
      text += `[${item.status || 'Pending'}] ${item.task} (Owner: ${item.owner}, Due: ${item.deadline})\n`;
    });
    text += `\n`;
  }

  if (meeting.transcript?.segments?.length) {
    text += `FULL TRANSCRIPT\n`;
    meeting.transcript.segments.forEach(seg => {
      const time = new Date(seg.start * 1000).toISOString().substr(14, 5);
      text += `[${time}] ${seg.speaker || 'Speaker'}: ${seg.text}\n`;
    });
  }

  const blob = new Blob([text], { type: 'text/plain;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${meeting.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_transcript.txt`;
  link.click();
};

export const exportToPDF = (meeting) => {
  const doc = new jsPDF();
  const lineHeight = 10;
  let y = 20;

  // Header
  doc.setFontSize(22);
  doc.setTextColor(79, 70, 229); // Indigo
  doc.text(meeting.title || 'Meeting Notes', 20, y);
  y += 10;
  
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Date: ${new Date(meeting.created_at || meeting.date).toLocaleDateString()} | Duration: ${meeting.duration || 'N/A'}`, 20, y);
  y += 15;

  // Summary
  doc.setFontSize(16);
  doc.setTextColor(0);
  doc.text("Executive Summary", 20, y);
  y += 10;
  
  doc.setFontSize(11);
  const summaryLines = doc.splitTextToSize(meeting.summary?.overview || 'No summary available.', 170);
  doc.text(summaryLines, 20, y);
  y += (summaryLines.length * 7) + 10;

  // Action Items
  if (meeting.actionItems?.length) {
    if (y > 250) { doc.addPage(); y = 20; }
    doc.setFontSize(16);
    doc.text("Action Items", 20, y);
    y += 10;
    
    doc.setFontSize(11);
    meeting.actionItems.forEach(item => {
      if (y > 270) { doc.addPage(); y = 20; }
      const itemText = `• ${item.task} (${item.owner})`;
      doc.text(itemText, 25, y);
      y += 7;
    });
    y += 10;
  }

  // Transcript
  if (meeting.transcript?.segments?.length) {
    doc.addPage();
    y = 20;
    doc.setFontSize(16);
    doc.text("Full Transcript", 20, y);
    y += 10;
    
    doc.setFontSize(10);
    meeting.transcript.segments.forEach(seg => {
      if (y > 270) { doc.addPage(); y = 20; }
      const time = new Date(seg.start * 1000).toISOString().substr(14, 5);
      const speaker = seg.speaker || 'Speaker';
      
      doc.setFont(undefined, 'bold');
      doc.text(`${time} ${speaker}:`, 20, y);
      
      doc.setFont(undefined, 'normal');
      const textLines = doc.splitTextToSize(seg.text, 130);
      doc.text(textLines, 60, y);
      
      y += (textLines.length * 5) + 3;
    });
  }

  // Footer
  const pageCount = doc.internal.getNumberOfPages();
  for(let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Generated by EchoNote AI - Page ${i} of ${pageCount}`, 105, 290, { align: 'center' });
  }

  doc.save(`${meeting.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.pdf`);
};

export const exportToDOCX = async (meeting) => {
  const children = [];

  // Title
  children.push(
    new Paragraph({
      text: meeting.title || 'Meeting Notes',
      heading: HeadingLevel.TITLE,
    }),
    new Paragraph({
      text: `Date: ${new Date(meeting.created_at || meeting.date).toLocaleDateString()} | Duration: ${meeting.duration || 'N/A'}`,
      spacing: { after: 300 },
    })
  );

  // Summary
  children.push(
    new Paragraph({
      text: "Executive Summary",
      heading: HeadingLevel.HEADING_1,
      spacing: { before: 200, after: 100 },
    }),
    new Paragraph({
      children: [new TextRun(meeting.summary?.overview || 'No summary available.')],
    })
  );

  // Action Items
  if (meeting.actionItems?.length) {
    children.push(
      new Paragraph({
        text: "Action Items",
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 300, after: 100 },
      })
    );

    const rows = [
      new TableRow({
        children: [
          new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "Task", bold: true })] })] }),
          new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "Owner", bold: true })] })] }),
          new TableCell({ children: [new Paragraph({ children: [new TextRun({ text: "Deadline", bold: true })] })] }),
        ],
      }),
    ];

    meeting.actionItems.forEach(item => {
      rows.push(
        new TableRow({
          children: [
            new TableCell({ children: [new Paragraph(item.task)] }),
            new TableCell({ children: [new Paragraph(item.owner || '-')] }),
            new TableCell({ children: [new Paragraph(item.deadline || '-')] }),
          ],
        })
      );
    });

    children.push(new Table({ rows: rows, width: { size: 100, type: "pct" } }));
  }

  // Transcript
  if (meeting.transcript?.segments?.length) {
    children.push(
      new Paragraph({
        text: "Full Transcript",
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 300, after: 100 },
      })
    );

    meeting.transcript.segments.forEach(seg => {
      const time = new Date(seg.start * 1000).toISOString().substr(14, 5);
      children.push(
        new Paragraph({
          children: [
            new TextRun({ text: `[${time}] ${seg.speaker || 'Speaker'}: `, bold: true }),
            new TextRun(seg.text),
          ],
          spacing: { after: 100 },
        })
      );
    });
  }

  // Footer
  children.push(
    new Paragraph({
      text: "Generated by EchoNote AI",
      spacing: { before: 500 },
      alignment: "center",
      style: "Subtitle"
    })
  );

  const doc = new Document({
    sections: [{ children: children }],
  });

  const blob = await Packer.toBlob(doc);
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${meeting.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.docx`;
  link.click();
};
