"""
Seed sample events data for Munal AI Events platform.
"""
import uuid
from datetime import datetime, timezone, timedelta

def _future(months):
    """Generate a future date N months from now."""
    now = datetime.now(timezone.utc)
    target = now.replace(day=15) + timedelta(days=months * 30)
    return target.isoformat()

def _future_end(months, hours=8):
    """Generate end date."""
    now = datetime.now(timezone.utc)
    target = now.replace(day=15) + timedelta(days=months * 30, hours=hours)
    return target.isoformat()

SAMPLE_EVENTS = [
    # ============ UPCOMING EVENTS ============
    {
        "id": str(uuid.uuid4()),
        "title": "AI Product Builder Bootcamp",
        "description": "A 2-day intensive bootcamp on building AI-first products. Learn from industry experts about LLM integration, prompt engineering, and shipping AI features at scale.",
        "category": "AI",
        "event_type": "Hybrid",
        "date": _future(1),
        "end_date": _future_end(1),
        "time": "9:00 AM EST",
        "duration": "2 Days",
        "location": "Toronto Convention Centre, Toronto, ON",
        "status": "registration_open",
        "price": "Free",
        "seats": 200,
        "registered": 142,
        "deadline": _future(1),
        "banner": "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800&q=80",
        "speakers": [
            {"name": "Dr. Sarah Chen", "title": "Head of AI, Shopify", "avatar": "https://i.pravatar.cc/150?img=1"},
            {"name": "Marcus Johnson", "title": "VP Engineering, Cohere", "avatar": "https://i.pravatar.cc/150?img=3"}
        ],
        "agenda": ["Opening Keynote", "Workshop: Building with LLMs", "Panel: AI Product Strategy", "Networking Lunch", "Hands-on Lab", "Closing & Certificates"],
        "faqs": [{"q": "Is this beginner-friendly?", "a": "Yes, we welcome all skill levels."}, {"q": "Will recordings be available?", "a": "Yes, all sessions will be recorded and shared with registered attendees."}],
        "tags": ["AI", "Product", "LLM", "Workshop"],
        "deleted": False
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Enterprise AI Agents Masterclass",
        "description": "Deep dive into building autonomous AI agents for enterprise workflows. Cover agent frameworks, tool use, RAG architectures, and production deployment patterns.",
        "category": "AI",
        "event_type": "Virtual",
        "date": _future(2),
        "end_date": _future_end(2),
        "time": "1:00 PM EST",
        "duration": "4 Hours",
        "location": "Online (Zoom)",
        "status": "registration_open",
        "price": "Free",
        "seats": 500,
        "registered": 287,
        "deadline": _future(2),
        "banner": "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=800&q=80",
        "speakers": [
            {"name": "Aisha Patel", "title": "AI Research Lead, Google DeepMind", "avatar": "https://i.pravatar.cc/150?img=5"},
            {"name": "James Liu", "title": "CTO, LangChain", "avatar": "https://i.pravatar.cc/150?img=8"}
        ],
        "agenda": ["AI Agents 101", "Framework Deep Dive", "RAG Architecture Patterns", "Live Coding Demo", "Q&A"],
        "faqs": [{"q": "What tools do I need?", "a": "A laptop with Python 3.10+ installed."}],
        "tags": ["AI", "Agents", "RAG", "Enterprise"],
        "deleted": False
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Cloud Native & Kubernetes Summit",
        "description": "Everything cloud-native: Kubernetes, service mesh, GitOps, platform engineering, and the future of infrastructure. Featuring live demos and hands-on workshops.",
        "category": "Cloud",
        "event_type": "Hybrid",
        "date": _future(3),
        "end_date": _future_end(3),
        "time": "9:00 AM EST",
        "duration": "Full Day",
        "location": "Mississauga Convention Centre, ON",
        "status": "registration_open",
        "price": "$49",
        "seats": 300,
        "registered": 156,
        "deadline": _future(3),
        "banner": "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&q=80",
        "speakers": [
            {"name": "Kelsey Hightower", "title": "Cloud Advocate", "avatar": "https://i.pravatar.cc/150?img=11"},
            {"name": "Priya Sharma", "title": "Platform Lead, Datadog", "avatar": "https://i.pravatar.cc/150?img=9"}
        ],
        "agenda": ["Keynote: Future of Cloud Native", "K8s Workshop", "Service Mesh Deep Dive", "GitOps in Practice", "Networking"],
        "faqs": [],
        "tags": ["Cloud", "Kubernetes", "DevOps", "Infrastructure"],
        "deleted": False
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Building AI SaaS Applications",
        "description": "From idea to revenue: learn to build, launch, and scale AI-powered SaaS products. Covering architecture, pricing, GTM strategy, and fundraising.",
        "category": "AI",
        "event_type": "Virtual",
        "date": _future(4),
        "end_date": _future_end(4),
        "time": "2:00 PM EST",
        "duration": "4 Hours",
        "location": "Online (Microsoft Teams)",
        "status": "registration_open",
        "price": "Free",
        "seats": 400,
        "registered": 203,
        "deadline": _future(4),
        "banner": "https://images.unsplash.com/photo-1551434678-e076c223a692?w=800&q=80",
        "speakers": [
            {"name": "Emily Zhang", "title": "Founder & CEO, NovaTech AI", "avatar": "https://i.pravatar.cc/150?img=20"},
            {"name": "David Kim", "title": "Partner, a16z", "avatar": "https://i.pravatar.cc/150?img=12"}
        ],
        "agenda": ["AI SaaS Landscape", "Technical Architecture", "Pricing Strategy", "GTM Playbook", "Fundraising Tips", "Live Q&A"],
        "faqs": [],
        "tags": ["AI", "SaaS", "Startup", "Business"],
        "deleted": False
    },
    {
        "id": str(uuid.uuid4()),
        "title": "DevOps & Platform Engineering Conference",
        "description": "The premier DevOps conference in Canada. CI/CD, IaC, observability, developer experience, and building internal developer platforms.",
        "category": "DevOps",
        "event_type": "In Person",
        "date": _future(5),
        "end_date": _future_end(5),
        "time": "9:00 AM EST",
        "duration": "2 Days",
        "location": "Metro Toronto Convention Centre",
        "status": "registration_open",
        "price": "$99",
        "seats": 500,
        "registered": 312,
        "deadline": _future(5),
        "banner": "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=800&q=80",
        "speakers": [
            {"name": "Alex Turner", "title": "VP DevOps, Stripe", "avatar": "https://i.pravatar.cc/150?img=15"},
            {"name": "Sofia Rodriguez", "title": "SRE Director, Netflix", "avatar": "https://i.pravatar.cc/150?img=23"}
        ],
        "agenda": ["Platform Engineering Keynote", "CI/CD Workshop", "Observability Deep Dive", "IaC Best Practices", "Networking Dinner"],
        "faqs": [],
        "tags": ["DevOps", "Platform", "CI/CD", "SRE"],
        "deleted": False
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Cybersecurity Threat Intelligence Forum",
        "description": "Expert-led sessions on threat intelligence, zero-trust architecture, incident response, and AI-powered security tools.",
        "category": "Cybersecurity",
        "event_type": "Virtual",
        "date": _future(6),
        "end_date": _future_end(6),
        "time": "10:00 AM EST",
        "duration": "6 Hours",
        "location": "Online (Zoom)",
        "status": "registration_open",
        "price": "Free",
        "seats": 600,
        "registered": 445,
        "deadline": _future(6),
        "banner": "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80",
        "speakers": [
            {"name": "Rachel Moore", "title": "CISO, RBC", "avatar": "https://i.pravatar.cc/150?img=25"},
            {"name": "Omar Hassan", "title": "Threat Intel Lead, CrowdStrike", "avatar": "https://i.pravatar.cc/150?img=17"}
        ],
        "agenda": ["Threat Landscape 2026", "Zero Trust Workshop", "AI in Security", "Incident Response Drill", "Panel Discussion"],
        "faqs": [],
        "tags": ["Cybersecurity", "Threat Intel", "Zero Trust"],
        "deleted": False
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Prompt Engineering Live Workshop",
        "description": "Master the art of prompt engineering. Hands-on sessions covering system prompts, chain-of-thought, few-shot learning, and advanced techniques for GPT, Claude, and Gemini.",
        "category": "AI",
        "event_type": "Hybrid",
        "date": _future(7),
        "end_date": _future_end(7),
        "time": "10:00 AM EST",
        "duration": "6 Hours",
        "location": "MaRS Discovery District, Toronto",
        "status": "registration_open",
        "price": "Free",
        "seats": 150,
        "registered": 98,
        "deadline": _future(7),
        "banner": "https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=800&q=80",
        "speakers": [
            {"name": "Lena Wei", "title": "AI Researcher, Anthropic", "avatar": "https://i.pravatar.cc/150?img=29"},
        ],
        "agenda": ["Prompt Fundamentals", "Advanced Techniques", "Hands-on Lab", "Real-world Case Studies", "Certification Exam"],
        "faqs": [],
        "tags": ["AI", "Prompt Engineering", "Workshop"],
        "deleted": False
    },
    {
        "id": str(uuid.uuid4()),
        "title": "AI Startup Founder Summit",
        "description": "Connect with 200+ AI founders, investors, and operators. Pitch competition, fireside chats, and exclusive networking with top VCs.",
        "category": "AI",
        "event_type": "Hybrid",
        "date": _future(8),
        "end_date": _future_end(8),
        "time": "9:00 AM EST",
        "duration": "Full Day",
        "location": "Evergreen Brick Works, Toronto",
        "status": "registration_open",
        "price": "$149",
        "seats": 250,
        "registered": 178,
        "deadline": _future(8),
        "banner": "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800&q=80",
        "speakers": [
            {"name": "Justin Ogala", "title": "CEO, Munal AI", "avatar": "https://i.pravatar.cc/150?img=33"},
            {"name": "Maria Santos", "title": "Managing Partner, Radical Ventures", "avatar": "https://i.pravatar.cc/150?img=32"}
        ],
        "agenda": ["Opening Keynote", "Pitch Competition", "Investor Panels", "Networking Lunch", "Fireside Chats", "Awards Ceremony"],
        "faqs": [],
        "tags": ["AI", "Startup", "Founder", "Investor"],
        "deleted": False
    },
    {
        "id": str(uuid.uuid4()),
        "title": "LLM Engineering Conference",
        "description": "Production-grade LLM engineering: fine-tuning, evaluation, guardrails, cost optimization, and building reliable AI systems at scale.",
        "category": "AI",
        "event_type": "Virtual",
        "date": _future(9),
        "end_date": _future_end(9),
        "time": "10:00 AM EST",
        "duration": "Full Day",
        "location": "Online (Zoom + Slack)",
        "status": "registration_open",
        "price": "Free",
        "seats": 1000,
        "registered": 623,
        "deadline": _future(9),
        "banner": "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=800&q=80",
        "speakers": [
            {"name": "Dr. Andrej Volkov", "title": "ML Engineering Lead, OpenAI", "avatar": "https://i.pravatar.cc/150?img=35"},
            {"name": "Tanya Nguyen", "title": "Head of AI Infra, Meta", "avatar": "https://i.pravatar.cc/150?img=36"}
        ],
        "agenda": ["LLM Ops Keynote", "Fine-tuning Workshop", "Evaluation Frameworks", "Cost Optimization", "Safety & Guardrails", "Panel: Future of LLMs"],
        "faqs": [],
        "tags": ["AI", "LLM", "Engineering", "MLOps"],
        "deleted": False
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Munal AI Annual Innovation Summit",
        "description": "The flagship Munal AI event. Product announcements, customer stories, workshops, and an exclusive look at the future of AI-powered workforce management.",
        "category": "AI",
        "event_type": "Hybrid",
        "date": _future(10),
        "end_date": _future_end(10),
        "time": "8:00 AM EST",
        "duration": "2 Days",
        "location": "Toronto Convention Centre, Hall A",
        "status": "registration_open",
        "price": "Free",
        "seats": 1500,
        "registered": 876,
        "deadline": _future(10),
        "banner": "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=800&q=80",
        "speakers": [
            {"name": "Justin Ogala", "title": "CEO, Munal AI", "avatar": "https://i.pravatar.cc/150?img=33"},
            {"name": "Dr. Fei Li", "title": "Chief Scientist, Munal AI", "avatar": "https://i.pravatar.cc/150?img=40"},
            {"name": "Kwame Asante", "title": "VP Product, Munal AI", "avatar": "https://i.pravatar.cc/150?img=41"}
        ],
        "agenda": ["Opening Keynote: Vision 2027", "Product Launch Demo", "Customer Spotlight", "AI Builder Workshop", "Partner Showcase", "Evening Gala"],
        "faqs": [{"q": "Is there a virtual option?", "a": "Yes, all main stage sessions will be live-streamed."}],
        "tags": ["AI", "Munal", "Innovation", "Conference"],
        "deleted": False
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Enterprise Automation Summit",
        "description": "Automate everything: RPA, intelligent document processing, workflow orchestration, and no-code/low-code platforms for the enterprise.",
        "category": "Software Engineering",
        "event_type": "Virtual",
        "date": _future(11),
        "end_date": _future_end(11),
        "time": "10:00 AM EST",
        "duration": "Full Day",
        "location": "Online (Microsoft Teams)",
        "status": "registration_open",
        "price": "Free",
        "seats": 800,
        "registered": 412,
        "deadline": _future(11),
        "banner": "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80",
        "speakers": [
            {"name": "Chris Anderson", "title": "CTO, UiPath", "avatar": "https://i.pravatar.cc/150?img=45"},
        ],
        "agenda": ["Automation Landscape", "RPA + AI Workshop", "IDP Deep Dive", "Low-Code Platforms", "Case Studies"],
        "faqs": [],
        "tags": ["Automation", "RPA", "Enterprise", "Low-Code"],
        "deleted": False
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Future of Artificial Intelligence Conference",
        "description": "Year-end mega conference exploring AGI, multimodal AI, AI regulation, ethical AI, and predictions for the year ahead.",
        "category": "AI",
        "event_type": "Hybrid",
        "date": _future(12),
        "end_date": _future_end(12),
        "time": "9:00 AM EST",
        "duration": "2 Days",
        "location": "Fairmont Royal York, Toronto",
        "status": "registration_open",
        "price": "$199",
        "seats": 600,
        "registered": 389,
        "deadline": _future(12),
        "banner": "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80",
        "speakers": [
            {"name": "Dr. Yoshua Bengio", "title": "Scientific Director, Mila", "avatar": "https://i.pravatar.cc/150?img=50"},
            {"name": "Timnit Gebru", "title": "Founder, DAIR Institute", "avatar": "https://i.pravatar.cc/150?img=48"}
        ],
        "agenda": ["AGI: Where Are We?", "Multimodal AI", "AI Ethics & Regulation", "Industry Panels", "Predictions 2027", "Closing Gala"],
        "faqs": [],
        "tags": ["AI", "AGI", "Ethics", "Future"],
        "deleted": False
    },
    # ============ PAST EVENTS ============
    {
        "id": str(uuid.uuid4()),
        "title": "AI for Healthcare Summit",
        "description": "How AI is transforming diagnostics, drug discovery, patient care, and healthcare operations.",
        "category": "AI",
        "event_type": "Hybrid",
        "date": "2025-03-15T09:00:00Z",
        "end_date": "2025-03-15T17:00:00Z",
        "time": "9:00 AM EST",
        "duration": "Full Day",
        "location": "MaRS Discovery District, Toronto",
        "status": "completed",
        "price": "Free",
        "seats": 300,
        "registered": 298,
        "banner": "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&q=80",
        "speakers": [{"name": "Dr. Lisa Park", "title": "Chief Medical AI Officer, UHN", "avatar": "https://i.pravatar.cc/150?img=55"}],
        "agenda": [], "faqs": [], "tags": ["AI", "Healthcare"], "deleted": False
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Open Source AI Conference",
        "description": "Celebrating open-source AI: Hugging Face, LLaMA, Mistral, and the open-source ecosystem driving AI innovation.",
        "category": "AI",
        "event_type": "Virtual",
        "date": "2025-05-20T10:00:00Z",
        "end_date": "2025-05-20T18:00:00Z",
        "time": "10:00 AM EST",
        "duration": "Full Day",
        "location": "Online",
        "status": "completed",
        "price": "Free",
        "seats": 2000,
        "registered": 1876,
        "banner": "https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=800&q=80",
        "speakers": [{"name": "Thomas Wolf", "title": "Co-founder, Hugging Face", "avatar": "https://i.pravatar.cc/150?img=57"}],
        "agenda": [], "faqs": [], "tags": ["AI", "Open Source"], "deleted": False
    },
    {
        "id": str(uuid.uuid4()),
        "title": "DevOps Leadership Forum",
        "description": "Leadership lessons from top engineering orgs. Building culture, scaling teams, and driving DevOps transformation.",
        "category": "DevOps",
        "event_type": "In Person",
        "date": "2025-06-12T09:00:00Z",
        "end_date": "2025-06-12T17:00:00Z",
        "time": "9:00 AM EST",
        "duration": "Full Day",
        "location": "The Westin Harbour Castle, Toronto",
        "status": "completed",
        "price": "$79",
        "seats": 200,
        "registered": 198,
        "banner": "https://images.unsplash.com/photo-1531482615713-2afd69097998?w=800&q=80",
        "speakers": [{"name": "Nicole Forsgren", "title": "VP Research, Microsoft", "avatar": "https://i.pravatar.cc/150?img=60"}],
        "agenda": [], "faqs": [], "tags": ["DevOps", "Leadership"], "deleted": False
    },
    {
        "id": str(uuid.uuid4()),
        "title": "AWS GenAI Bootcamp",
        "description": "Hands-on workshop building generative AI applications on AWS using Bedrock, SageMaker, and Lambda.",
        "category": "Cloud",
        "event_type": "Hybrid",
        "date": "2025-07-10T09:00:00Z",
        "end_date": "2025-07-10T17:00:00Z",
        "time": "9:00 AM EST",
        "duration": "Full Day",
        "location": "AWS Loft, Toronto",
        "status": "completed",
        "price": "Free",
        "seats": 100,
        "registered": 100,
        "banner": "https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=800&q=80",
        "speakers": [{"name": "Swami Sivasubramanian", "title": "VP AI/ML, AWS", "avatar": "https://i.pravatar.cc/150?img=62"}],
        "agenda": [], "faqs": [], "tags": ["Cloud", "AWS", "GenAI"], "deleted": False
    },
    {
        "id": str(uuid.uuid4()),
        "title": "AI in Finance Conference",
        "description": "AI applications in fintech, algorithmic trading, fraud detection, risk management, and regulatory compliance.",
        "category": "AI",
        "event_type": "Hybrid",
        "date": "2025-09-08T09:00:00Z",
        "end_date": "2025-09-08T17:00:00Z",
        "time": "9:00 AM EST",
        "duration": "Full Day",
        "location": "TMX Broadcast Centre, Toronto",
        "status": "completed",
        "price": "$129",
        "seats": 250,
        "registered": 234,
        "banner": "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80",
        "speakers": [{"name": "Rebecca Torres", "title": "Head of AI, TD Bank", "avatar": "https://i.pravatar.cc/150?img=65"}],
        "agenda": [], "faqs": [], "tags": ["AI", "Finance", "Fintech"], "deleted": False
    },
    {
        "id": str(uuid.uuid4()),
        "title": "Cybersecurity Leadership Forum",
        "description": "Executive-level cybersecurity discussions on zero-trust, supply chain security, and building resilient organizations.",
        "category": "Cybersecurity",
        "event_type": "In Person",
        "date": "2025-10-22T09:00:00Z",
        "end_date": "2025-10-22T17:00:00Z",
        "time": "9:00 AM EST",
        "duration": "Full Day",
        "location": "Shangri-La Hotel, Toronto",
        "status": "completed",
        "price": "$199",
        "seats": 150,
        "registered": 148,
        "banner": "https://images.unsplash.com/photo-1563986768609-322da13575f2?w=800&q=80",
        "speakers": [{"name": "Mike Johnson", "title": "CISO, Scotiabank", "avatar": "https://i.pravatar.cc/150?img=68"}],
        "agenda": [], "faqs": [], "tags": ["Cybersecurity", "Leadership"], "deleted": False
    },
]


async def seed_events(db):
    """Seed events if collection is empty"""
    count = await db.events.count_documents({})
    if count > 0:
        return False
    await db.events.insert_many(SAMPLE_EVENTS)
    return True
