#!/usr/bin/env python3
"""Seed: Digital Marketing + Design + Media courses"""
import sys, requests, json
API_URL, TOKEN = sys.argv[1], sys.argv[2]
H = {"Authorization": f"Bearer {TOKEN}", "Content-Type": "application/json"}

def q(question, opts, correct, expl):
    return {"question": question, "options": opts, "correct_answer": correct, "explanation": expl}

def lesson(title, url, dur, order, quiz):
    return {"title": title, "video_url": url, "duration": dur, "type": "video", "order": order, "quiz": quiz}

def course(title, desc, cat, level, thumb, tags, instructor, inst_title, hours, lessons, threshold=70):
    return {"title": title, "description": desc, "category": cat, "level": level, "is_premium": False, "price": 0, "instructor_name": instructor, "instructor_avatar": f"https://randomuser.me/api/portraits/{'men' if hash(instructor) % 2 == 0 else 'women'}/{abs(hash(instructor)) % 90}.jpg", "instructor_title": inst_title, "thumbnail": thumb, "tags": tags, "what_you_learn": [t.strip() for t in desc.split('.')[0:2]], "prerequisites": ["None"], "estimated_hours": hours, "status": "published", "pass_threshold": threshold, "lessons": lessons}

COURSES = [
    # === DIGITAL MARKETING ===
    course("SEO Fundamentals - Search Engine Optimization", "Learn how to rank your website on Google. Covers keyword research, on-page SEO, technical SEO, link building, and content optimization strategies.", "Digital Marketing", "beginner", "https://images.unsplash.com/photo-1432888622747-4eb9a8efeb07?w=600&q=80", ["SEO", "Google", "Marketing"], "Brian Dean", "SEO Expert & Backlinko Founder", 5, [
        lesson("SEO Full Course for Beginners", "https://www.youtube.com/watch?v=xsVTqzratPs", "40 min", 0, [
            q("What does SEO stand for?", ["Social Engine Optimization", "Search Engine Optimization", "Site Enhancement Online", "Search Email Outreach"], 1, "SEO = Search Engine Optimization — the practice of improving website visibility in search results."),
            q("What is a keyword in SEO?", ["A password", "A word or phrase users type into search engines", "A meta tag", "A domain name"], 1, "Keywords are the search terms people use; optimizing for them helps your content appear in relevant searches."),
            q("What is backlink building?", ["Creating internal links", "Getting other websites to link to your site to boost authority", "Linking to social media", "Adding footer links"], 1, "Backlinks from reputable sites signal trust to search engines, improving your rankings.")]),
        lesson("Keyword Research Tutorial", "https://www.youtube.com/watch?v=OMJQPqG2Uas", "20 min", 1, [
            q("What tool is commonly used for keyword research?", ["Photoshop", "Google Keyword Planner", "Excel", "Slack"], 1, "Google Keyword Planner is a free tool that shows search volume and competition for keywords."),
            q("What is search intent?", ["SEO ranking factor", "The reason behind a user's search query", "A Google algorithm", "A type of keyword"], 1, "Search intent is why someone searches — informational, navigational, commercial, or transactional.")])]),
    course("Google Ads - Complete PPC Advertising Course", "Master Google Ads from setup to optimization. Learn search ads, display campaigns, shopping ads, YouTube ads, bidding strategies, and conversion tracking.", "Digital Marketing", "intermediate", "https://images.unsplash.com/photo-1563986768609-322da13575f2?w=600&q=80", ["Google Ads", "PPC", "Advertising"], "Aaron Young", "Google Ads Specialist", 6, [
        lesson("Google Ads Tutorial - Complete Course", "https://www.youtube.com/watch?v=oQw8pn-xgZY", "45 min", 0, [
            q("What does PPC stand for?", ["Pay Per Click", "Price Per Campaign", "Paid Page Content", "Post Per Click"], 0, "PPC = Pay Per Click — you pay each time someone clicks your ad."),
            q("What is Quality Score in Google Ads?", ["Ad budget rating", "Google's rating of ad relevance, landing page, and expected CTR", "Number of clicks", "Campaign duration"], 1, "Quality Score affects ad rank and cost-per-click — higher scores mean better positions at lower costs."),
            q("What is a conversion in Google Ads?", ["A page view", "A desired action taken by a user after clicking an ad", "An ad impression", "A keyword match"], 1, "A conversion is any valuable action — purchase, signup, call — tracked to measure ad effectiveness.")])]),
    course("Facebook & Instagram Ads Mastery", "Create high-performing Facebook and Instagram ad campaigns. Learn audience targeting, ad creative, pixel setup, retargeting, lookalike audiences, and campaign optimization.", "Digital Marketing", "intermediate", "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=600&q=80", ["Facebook Ads", "Instagram", "Social Media"], "Coursenvy", "Social Media Marketing Expert", 5, [
        lesson("Facebook Ads Full Course", "https://www.youtube.com/watch?v=o-gKCmFnOPI", "40 min", 0, [
            q("What is Facebook Pixel?", ["A camera feature", "A tracking code for measuring ad conversions and building audiences", "A photo filter", "An ad format"], 1, "Facebook Pixel tracks user actions on your website, enabling conversion tracking and retargeting."),
            q("What is a lookalike audience?", ["Your existing customers", "People similar to your best customers found by Facebook's algorithm", "Random users", "Email subscribers"], 1, "Lookalike audiences find new people who share characteristics with your existing customers.")])]),
    course("LinkedIn Marketing & Lead Generation", "Leverage LinkedIn for B2B marketing and lead generation. Covers profile optimization, content strategy, LinkedIn Ads, Sales Navigator, and building professional authority.", "Digital Marketing", "beginner", "https://images.unsplash.com/photo-1611944212129-29977ae1398c?w=600&q=80", ["LinkedIn", "B2B", "Lead Generation"], "Tim Queen", "LinkedIn Strategist", 3, [
        lesson("LinkedIn Marketing Full Course", "https://www.youtube.com/watch?v=sXA1eaqogKU", "30 min", 0, [
            q("What type of marketing is LinkedIn best for?", ["B2C retail", "B2B professional marketing and lead generation", "Food delivery", "Gaming"], 1, "LinkedIn is the premier B2B platform with 900M+ professionals — ideal for business marketing and recruiting."),
            q("What is LinkedIn Sales Navigator?", ["A GPS tool", "A premium tool for finding and engaging prospects", "A free messaging app", "An ad platform"], 1, "Sales Navigator provides advanced search, lead recommendations, and InMail for sales prospecting.")])]),
    course("Email Marketing - From Beginner to Pro", "Build effective email marketing campaigns. Learn list building, segmentation, automation, copywriting, A/B testing, deliverability, and measuring email marketing ROI.", "Digital Marketing", "beginner", "https://images.unsplash.com/photo-1596526131083-e8c633c948d2?w=600&q=80", ["Email Marketing", "Automation", "Copywriting"], "Alex Cattoni", "Marketing Strategist", 4, [
        lesson("Email Marketing Full Course", "https://www.youtube.com/watch?v=Oj0FMPSdcRo", "35 min", 0, [
            q("What is the most important metric in email marketing?", ["Number of emails sent", "Open rate and click-through rate", "List size", "Design quality"], 1, "Open rate shows how many people read your email; CTR shows how many take action — both indicate effectiveness."),
            q("What is email segmentation?", ["Splitting emails in half", "Dividing your list into groups based on characteristics for targeted messaging", "Deleting inactive subscribers", "A spam filter"], 1, "Segmentation sends relevant content to specific groups, dramatically improving engagement and conversions.")])]),
    course("Content Marketing Strategy", "Create a winning content marketing strategy. Learn content planning, SEO content writing, blog management, content distribution, repurposing, and measuring content ROI.", "Digital Marketing", "beginner", "https://images.unsplash.com/photo-1455849318743-b2233052fcff?w=600&q=80", ["Content Marketing", "Blogging", "Strategy"], "Neil Patel", "Digital Marketing Expert", 4, [
        lesson("Content Marketing Full Course", "https://www.youtube.com/watch?v=p11Fgbsihdo", "30 min", 0, [
            q("What is content marketing?", ["Advertising", "Creating valuable content to attract and retain an audience", "Social media posting", "Email blasts"], 1, "Content marketing creates and distributes valuable, relevant content to attract and engage a target audience."),
            q("What is a content calendar?", ["A holiday schedule", "A planning tool organizing when and where to publish content", "A social media app", "An analytics dashboard"], 1, "A content calendar plans content creation and publication across channels, ensuring consistency and strategy alignment.")])]),
    course("Copywriting - Write to Sell", "Master the art of persuasive writing for marketing. Learn headline formulas, emotional triggers, storytelling, landing page copy, email copy, and direct response copywriting techniques.", "Digital Marketing", "intermediate", "https://images.unsplash.com/photo-1455390582262-044cdead277a?w=600&q=80", ["Copywriting", "Marketing", "Writing"], "Alex Cattoni", "Copywriting Coach", 4, [
        lesson("Copywriting Full Course", "https://www.youtube.com/watch?v=7Qx1TNS3yZw", "35 min", 0, [
            q("What is the AIDA framework?", ["A music app", "Attention, Interest, Desire, Action - a copywriting formula", "A design tool", "An analytics method"], 1, "AIDA guides readers through a journey: grab Attention, build Interest, create Desire, prompt Action."),
            q("What makes a great headline?", ["Being long and detailed", "Being specific, creating curiosity, and promising a benefit", "Using all caps", "Including the company name"], 1, "Great headlines are specific, evoke curiosity or emotion, and clearly communicate the value to the reader.")])]),
    course("Google Analytics 4 - Complete Guide", "Master Google Analytics 4 (GA4) for data-driven marketing. Learn event tracking, user journeys, custom reports, conversions, audiences, and attribution modeling.", "Digital Marketing", "intermediate", "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&q=80", ["Analytics", "GA4", "Data", "Marketing"], "Loves Data", "Analytics Specialist", 5, [
        lesson("Google Analytics 4 Full Course", "https://www.youtube.com/watch?v=u4kXjMOhRPM", "40 min", 0, [
            q("What replaced Universal Analytics?", ["Google Ads", "Google Analytics 4 (GA4)", "Google Search Console", "Google Tag Manager"], 1, "GA4 replaced Universal Analytics with an event-based model for better cross-platform tracking."),
            q("What is an 'event' in GA4?", ["A calendar appointment", "Any user interaction tracked on your website or app", "A marketing campaign", "A server request"], 1, "In GA4, everything is an event — page views, clicks, scrolls, purchases — providing flexible tracking.")])]),
    course("Marketing Automation with HubSpot", "Automate your marketing workflows. Learn lead nurturing, email sequences, CRM integration, lead scoring, chatbots, and building automated customer journeys.", "Digital Marketing", "intermediate", "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=600&q=80", ["Automation", "HubSpot", "CRM", "Lead Nurturing"], "HubSpot Academy", "Marketing Platform", 4, [
        lesson("Marketing Automation Full Course", "https://www.youtube.com/watch?v=7vJWJo23pQw", "30 min", 0, [
            q("What is marketing automation?", ["Posting on social media", "Using software to automate repetitive marketing tasks and workflows", "Hiring more staff", "Manual email sends"], 1, "Marketing automation uses software to automate tasks like email campaigns, lead nurturing, and social posting."),
            q("What is lead scoring?", ["Rating lead quality", "Assigning points to leads based on behavior and demographics to prioritize sales efforts", "Counting leads", "A sports term"], 1, "Lead scoring ranks prospects by engagement level and fit, helping sales focus on the most promising leads.")])]),
    course("Branding & Brand Strategy", "Build a powerful brand from scratch. Learn brand positioning, visual identity, brand voice, storytelling, brand guidelines, and creating emotional connections with your audience.", "Digital Marketing", "beginner", "https://images.unsplash.com/photo-1558655146-9f40138edfeb?w=600&q=80", ["Branding", "Strategy", "Identity", "Marketing"], "Philip VanDusen", "Brand Strategist", 3, [
        lesson("Brand Strategy Full Course", "https://www.youtube.com/watch?v=mO_QXbCMZ8o", "30 min", 0, [
            q("What is brand positioning?", ["Physical store location", "How your brand is perceived relative to competitors in customers' minds", "A logo design", "A pricing strategy"], 1, "Brand positioning defines the unique space your brand occupies in the market and in consumers' minds."),
            q("What is a brand style guide?", ["A fashion magazine", "A document defining visual and verbal rules for consistent brand communication", "A website template", "A marketing plan"], 1, "A brand style guide ensures consistency across all touchpoints with rules for logos, colors, fonts, and tone of voice.")])]),

    # === DESIGN ===
    course("UI/UX Design Fundamentals", "Learn user interface and user experience design from scratch. Covers design thinking, wireframing, prototyping, usability testing, design systems, and modern UI patterns.", "Design", "beginner", "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600&q=80", ["UI/UX", "Design", "Wireframing", "Prototyping"], "Gary Simon", "UI/UX Designer & Educator", 6, [
        lesson("UI/UX Design Full Course", "https://www.youtube.com/watch?v=68w2VwalD5w", "45 min", 0, [
            q("What is the difference between UI and UX?", ["No difference", "UI is visual design; UX is the overall user experience and journey", "UI is coding; UX is design", "They are unrelated"], 1, "UI focuses on visual elements (buttons, colors, layouts); UX covers the entire user journey and satisfaction."),
            q("What is wireframing?", ["Building fences", "Creating low-fidelity layouts to plan page structure before detailed design", "Writing code", "Testing software"], 1, "Wireframes are simplified visual guides showing page layout, content placement, and functionality without visual design."),
            q("What is usability testing?", ["Load testing", "Observing real users interacting with a product to find issues", "Unit testing", "A/B testing"], 1, "Usability testing watches real users complete tasks, revealing friction points and improvement opportunities.")])]),
    course("Figma - Complete UI Design Tool", "Master Figma for professional UI design. Learn components, auto layout, prototyping, design systems, collaboration, plugins, and responsive design techniques.", "Design", "beginner", "https://images.unsplash.com/photo-1609921212029-bb5a28e60960?w=600&q=80", ["Figma", "UI Design", "Prototyping", "Design System"], "DesignCourse", "Design Educator", 6, [
        lesson("Figma Full Course - UI Design Tutorial", "https://www.youtube.com/watch?v=jwCmIBJ8Jtc", "40 min", 0, [
            q("What is Figma?", ["A programming language", "A collaborative interface design tool that runs in the browser", "A photo editor", "A code editor"], 1, "Figma is a browser-based design tool for UI/UX with real-time collaboration, prototyping, and design systems."),
            q("What is Auto Layout in Figma?", ["Automatic file saving", "A feature that makes frames resize dynamically based on content", "A grid system", "An animation tool"], 1, "Auto Layout makes frames respond to content changes automatically, similar to CSS flexbox in web development."),
            q("What are Figma Components?", ["Hardware parts", "Reusable design elements that stay in sync across your project", "Code libraries", "Font files"], 1, "Components are reusable elements — edit the main component and all instances update automatically.")])]),
    course("Adobe Photoshop for Beginners", "Learn Photoshop from scratch. Master layers, selections, masking, retouching, compositing, text effects, and export for web and print.", "Design", "beginner", "https://images.unsplash.com/photo-1572044162444-ad60f128bdea?w=600&q=80", ["Photoshop", "Adobe", "Photo Editing", "Design"], "Envato Tuts+", "Creative Skills Platform", 6, [
        lesson("Photoshop Tutorial for Beginners", "https://www.youtube.com/watch?v=IyR_uYsRdPs", "40 min", 0, [
            q("What are layers in Photoshop?", ["Background colors", "Transparent sheets stacked on top of each other for non-destructive editing", "File formats", "Selection tools"], 1, "Layers allow you to work on different elements independently without affecting other parts of your design."),
            q("What is a layer mask?", ["A filter", "A non-destructive way to hide or reveal parts of a layer", "A color adjustment", "A file format"], 1, "Layer masks use black (hide) and white (reveal) to control visibility of layer parts without deleting pixels.")])]),
    course("Canva Design Masterclass", "Create professional graphics with Canva. Learn social media designs, presentations, videos, brand kits, templates, animations, and print materials — no design experience needed.", "Design", "beginner", "https://images.unsplash.com/photo-1626785774573-4b799315345d?w=600&q=80", ["Canva", "Graphic Design", "Social Media", "Templates"], "Ronny Media", "Digital Design Educator", 3, [
        lesson("Canva Full Course - Beginner to Pro", "https://www.youtube.com/watch?v=4Mo3Rmxcefo", "35 min", 0, [
            q("What is Canva best used for?", ["Video editing", "Quick professional graphic design for non-designers", "3D modeling", "Coding"], 1, "Canva is a drag-and-drop design tool perfect for creating social media graphics, presentations, and marketing materials."),
            q("What is a Canva Brand Kit?", ["A physical kit", "A set of saved brand colors, fonts, and logos for consistent designs", "A template pack", "A subscription"], 1, "Brand Kit stores your brand's colors, fonts, and logos so every design stays on-brand with one click.")])]),
    course("Logo Design & Brand Identity", "Design professional logos and brand identities. Learn logo types, design principles, color psychology, typography, presenting to clients, and creating complete brand identity packages.", "Design", "intermediate", "https://images.unsplash.com/photo-1626785774625-ddcddc3445e9?w=600&q=80", ["Logo Design", "Branding", "Identity", "Design"], "Will Paterson", "Logo Designer", 4, [
        lesson("Logo Design Full Course", "https://www.youtube.com/watch?v=mBZSjSwBcuo", "35 min", 0, [
            q("What are the main types of logos?", ["Only text logos", "Wordmark, lettermark, icon, combination mark, and emblem", "Only icons", "Only abstract shapes"], 1, "Logo types include wordmarks (Google), lettermarks (IBM), icons (Apple), combination marks (Adidas), and emblems (Starbucks)."),
            q("What is the golden ratio in logo design?", ["A price point", "A mathematical ratio (~1.618) used to create visually harmonious proportions", "A color scheme", "A font size"], 1, "The golden ratio (1:1.618) creates naturally pleasing proportions and is used by many iconic logos.")])]),
    course("Motion Graphics & After Effects", "Create stunning motion graphics and animations. Learn After Effects fundamentals, kinetic typography, shape animations, logo reveals, and export for social media and web.", "Design", "intermediate", "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=600&q=80", ["Motion Graphics", "After Effects", "Animation", "Design"], "Ben Marriott", "Motion Designer", 6, [
        lesson("After Effects for Beginners - Full Course", "https://www.youtube.com/watch?v=RqHRmqHJMuw", "40 min", 0, [
            q("What is After Effects primarily used for?", ["Photo editing", "Motion graphics, visual effects, and animation", "3D modeling", "Audio editing"], 1, "After Effects is Adobe's industry-standard tool for creating motion graphics, animations, and visual effects."),
            q("What are keyframes?", ["Key on a keyboard", "Markers that define the start and end points of an animation", "A file format", "A layer type"], 1, "Keyframes mark specific values at specific times — After Effects interpolates the animation between them.")])]),
    course("Product Design - From Idea to Launch", "End-to-end product design process. Learn user research, information architecture, interaction design, visual design, design systems, handoff to developers, and measuring design impact.", "Design", "intermediate", "https://images.unsplash.com/photo-1586717791821-3f44a563fa4c?w=600&q=80", ["Product Design", "UX Research", "Design Systems"], "AJ&Smart", "Product Design Agency", 5, [
        lesson("Product Design Process - Full Guide", "https://www.youtube.com/watch?v=oRxHvXosfNg", "30 min", 0, [
            q("What is the double diamond design process?", ["A jewelry technique", "Discover, Define, Develop, Deliver — divergent and convergent thinking phases", "A coding pattern", "A testing method"], 1, "The double diamond has 4 phases: Discover (research), Define (problem), Develop (solutions), Deliver (implement)."),
            q("What is a design system?", ["A design tool", "A collection of reusable components and guidelines for consistent product design", "A project plan", "A wireframe"], 1, "A design system provides reusable components, patterns, and guidelines ensuring consistency across products.")])]),

    # === MEDIA ===
    course("Video Editing with DaVinci Resolve", "Learn professional video editing with the free DaVinci Resolve. Master the cut page, edit page, color grading, audio mixing, visual effects, and delivering final exports.", "Media", "beginner", "https://images.unsplash.com/photo-1574717024653-61fd2cf4d44d?w=600&q=80", ["Video Editing", "DaVinci Resolve", "Color Grading"], "Casey Faris", "Video Editor & YouTuber", 7, [
        lesson("DaVinci Resolve Full Course for Beginners", "https://www.youtube.com/watch?v=UguJiz9AYM8", "45 min", 0, [
            q("What makes DaVinci Resolve unique?", ["It's paid only", "It's a free professional editor with industry-leading color grading", "It only does audio", "It's mobile only"], 1, "DaVinci Resolve offers professional editing, color grading, VFX, and audio in one free application."),
            q("What is color grading?", ["Scoring a test", "Adjusting colors to create a specific look, mood, or correct exposure", "A printing technique", "A camera setting"], 1, "Color grading enhances or stylizes footage by adjusting color, contrast, and tone to set the visual mood.")])]),
    course("YouTube Creator - Grow Your Channel", "Build and grow a successful YouTube channel. Learn content strategy, thumbnails, SEO, analytics, monetization, equipment, and audience engagement techniques.", "Media", "beginner", "https://images.unsplash.com/photo-1611162616475-46b635cb6868?w=600&q=80", ["YouTube", "Content Creation", "Video", "Monetization"], "Ali Abdaal", "YouTuber & Educator", 4, [
        lesson("How to Start a YouTube Channel - Complete Guide", "https://www.youtube.com/watch?v=XpopyNZKYKw", "35 min", 0, [
            q("What is the most important factor for YouTube growth?", ["Upload frequency", "Click-through rate (CTR) on thumbnails combined with watch time", "Subscriber count", "Video length"], 1, "YouTube's algorithm prioritizes videos with high CTR (compelling thumbnails/titles) and high audience retention."),
            q("What is YouTube SEO?", ["A paid feature", "Optimizing titles, descriptions, and tags so videos appear in search results", "A video format", "An editing technique"], 1, "YouTube SEO helps your videos rank in search by using relevant keywords in titles, descriptions, tags, and chapters.")])]),
    course("Podcasting - Start to Monetize", "Launch and grow a professional podcast. Learn recording, editing, hosting, distribution, audience growth, monetization, interview techniques, and podcast branding.", "Media", "beginner", "https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=600&q=80", ["Podcasting", "Audio", "Content Creation"], "Pat Flynn", "Podcaster & Entrepreneur", 4, [
        lesson("How to Start a Podcast - Complete Guide", "https://www.youtube.com/watch?v=RfnRESwRa44", "30 min", 0, [
            q("What equipment is essential for starting a podcast?", ["Professional studio", "A decent USB microphone and recording software", "Expensive mixer", "Video camera"], 1, "A quality USB mic (like Blue Yeti or Audio-Technica) and free software like Audacity is enough to start."),
            q("What is a podcast hosting platform?", ["A recording studio", "A service that stores audio files and distributes to Apple, Spotify, etc.", "A social network", "An editing tool"], 1, "Podcast hosts store your files and generate RSS feeds that distribute episodes to all major platforms.")])]),
    course("OBS Studio - Live Streaming & Recording", "Master OBS Studio for live streaming and screen recording. Learn scene setup, sources, audio mixing, transitions, streaming to multiple platforms, and recording optimization.", "Media", "beginner", "https://images.unsplash.com/photo-1587620962725-abab7fe55159?w=600&q=80", ["OBS Studio", "Streaming", "Recording", "Live"], "EposVox", "Streaming Tech Expert", 3, [
        lesson("OBS Studio Complete Tutorial", "https://www.youtube.com/watch?v=nK-Wn3U3jRo", "30 min", 0, [
            q("What is OBS Studio?", ["A music app", "Free open-source software for video recording and live streaming", "A paid editor", "A camera app"], 1, "OBS (Open Broadcaster Software) is free, open-source software for recording and live streaming video."),
            q("What is a 'Scene' in OBS?", ["A movie scene", "A collection of sources (camera, screen, images) that make up your stream layout", "A video clip", "A transition effect"], 1, "Scenes are preset layouts containing various sources — you switch between scenes during your stream.")])]),
    course("CapCut Video Editing - Mobile & Desktop", "Edit professional videos with CapCut. Learn cuts, transitions, effects, text animations, green screen, speed ramping, and trending TikTok/Reels editing techniques.", "Media", "beginner", "https://images.unsplash.com/photo-1536240478700-b869070f9279?w=600&q=80", ["CapCut", "Video Editing", "TikTok", "Reels"], "Justin Brown", "Video Creator", 3, [
        lesson("CapCut Editing Tutorial - Full Course", "https://www.youtube.com/watch?v=W64etMKG1FQ", "25 min", 0, [
            q("What platforms is CapCut available on?", ["iOS only", "Mobile (iOS/Android) and Desktop — free to use", "Windows only", "Paid subscription only"], 1, "CapCut is free on iOS, Android, and desktop — created by ByteDance (TikTok's parent company)."),
            q("What is speed ramping?", ["Running fast", "Smoothly transitioning between slow motion and normal speed in a clip", "Uploading quickly", "Fast forwarding"], 1, "Speed ramping creates dynamic transitions by smoothly changing clip speed — popular in action and travel videos.")])]),
    course("Storytelling for Video & Content", "Master the art of storytelling for digital content. Learn narrative structure, emotional hooks, visual storytelling, scripting, pacing, and creating content that connects with audiences.", "Media", "intermediate", "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=600&q=80", ["Storytelling", "Content", "Narrative", "Video"], "Film Riot", "Filmmaking Educator", 3, [
        lesson("Storytelling Techniques for Creators", "https://www.youtube.com/watch?v=Nj-hdQMa3uA", "25 min", 0, [
            q("What is the three-act structure?", ["Three video clips", "Setup, Confrontation, Resolution — a classic narrative framework", "Three cameras", "Three editors"], 1, "The three-act structure (beginning, middle, end) creates compelling narratives with clear tension and resolution."),
            q("What is a 'hook' in content creation?", ["A fishing tool", "An attention-grabbing opening that makes viewers want to keep watching", "A transition effect", "A call to action"], 1, "A hook captures attention in the first 3-5 seconds — essential for social media where scroll speed is fast.")])]),
]

for c in COURSES:
    r = requests.post(f"{API_URL}/api/academy/admin/courses", headers=H, json=c)
    status = "OK" if r.status_code == 200 else "FAIL"
    print(f"  [{status}] {c['title'][:50]}")
print(f"\nDone! Seeded {len(COURSES)} courses.")
