#!/usr/bin/env python3
"""Seed: Engineering + Construction + Logistics + Finance + Legal courses"""
import sys, requests
API_URL, TOKEN = sys.argv[1], sys.argv[2]
H = {"Authorization": f"Bearer {TOKEN}", "Content-Type": "application/json"}

def q(question, opts, correct, expl):
    return {"question": question, "options": opts, "correct_answer": correct, "explanation": expl}

def lesson(title, url, dur, order, quiz):
    return {"title": title, "video_url": url, "duration": dur, "type": "video", "order": order, "quiz": quiz}

def course(title, desc, cat, level, thumb, tags, instructor, inst_title, hours, lessons, threshold=70):
    return {"title": title, "description": desc, "category": cat, "level": level, "is_premium": False, "price": 0, "instructor_name": instructor, "instructor_avatar": f"https://randomuser.me/api/portraits/{'men' if hash(instructor) % 2 == 0 else 'women'}/{abs(hash(instructor)) % 90}.jpg", "instructor_title": inst_title, "thumbnail": thumb, "tags": tags, "what_you_learn": [t.strip() for t in desc.split('.')[0:2]], "prerequisites": ["None"], "estimated_hours": hours, "status": "published", "pass_threshold": threshold, "lessons": lessons}

COURSES = [
    # === ENGINEERING ===
    course("AutoCAD for Beginners", "Learn AutoCAD fundamentals for 2D drafting and 3D modeling. Master drawing tools, dimensions, layers, blocks, layouts, and plotting for architectural and engineering drawings.", "Engineering", "beginner", "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=600&q=80", ["AutoCAD", "CAD", "Drafting", "Engineering"], "CAD in Black", "AutoCAD Specialist", 6, [
        lesson("AutoCAD Full Course for Beginners", "https://www.youtube.com/watch?v=VtLXKU1PorQ", "45 min", 0, [
            q("What is AutoCAD used for?", ["Photo editing", "2D drafting and 3D computer-aided design for engineering and architecture", "Video editing", "Web design"], 1, "AutoCAD is Autodesk's industry-standard CAD software for creating precise 2D and 3D technical drawings."),
            q("What is a layer in AutoCAD?", ["A physical sheet", "An organizational tool to group and control visibility of drawing elements", "A 3D surface", "A file type"], 1, "Layers organize drawing elements — you can control color, line type, and visibility of objects on each layer."),
            q("What command draws a straight line?", ["CIRCLE", "LINE", "ARC", "SPLINE"], 1, "The LINE command draws straight line segments — the most fundamental drawing command in AutoCAD.")])]),
    course("SolidWorks Essentials", "Learn 3D CAD modeling with SolidWorks. Covers sketching, part modeling, assemblies, drawings, sheet metal, and design analysis for mechanical engineering.", "Engineering", "intermediate", "https://images.unsplash.com/photo-1581093458791-9f3c3900df4b?w=600&q=80", ["SolidWorks", "3D CAD", "Mechanical", "Engineering"], "CADimensions", "SolidWorks Trainer", 7, [
        lesson("SolidWorks Full Course for Beginners", "https://www.youtube.com/watch?v=LE1LaB1JQYY", "45 min", 0, [
            q("What type of modeling does SolidWorks primarily use?", ["Surface modeling", "Parametric solid modeling", "Mesh modeling", "Sculpting"], 1, "SolidWorks uses parametric solid modeling where features are defined by dimensions that can be changed anytime."),
            q("What is a sketch in SolidWorks?", ["A freehand drawing", "A 2D profile on a plane that defines the shape for 3D features", "A rendered image", "A simulation"], 1, "Sketches are 2D profiles drawn on planes that become the basis for 3D features like extrudes and revolves.")])]),
    course("Revit for Architecture", "Master Autodesk Revit for Building Information Modeling (BIM). Learn architectural modeling, families, schedules, sheets, rendering, and collaborative BIM workflows.", "Engineering", "intermediate", "https://images.unsplash.com/photo-1487958449943-2429e8be8625?w=600&q=80", ["Revit", "BIM", "Architecture", "Engineering"], "Balkan Architect", "BIM Specialist", 7, [
        lesson("Revit Full Course for Beginners", "https://www.youtube.com/watch?v=FtJWrMoFEi8", "45 min", 0, [
            q("What is BIM?", ["A construction tool", "Building Information Modeling — 3D model-based process for building design", "A file format", "A building code"], 1, "BIM creates intelligent 3D models containing real building data — materials, costs, scheduling — beyond just geometry."),
            q("What is a Revit Family?", ["A user group", "A parametric component (door, window, furniture) with adjustable properties", "A project template", "A view type"], 1, "Families are reusable, parametric components — from doors to structural columns — that contain geometry and data.")])]),
    course("Electrical Engineering Basics", "Fundamentals of electrical engineering. Learn circuit analysis, Ohm's law, AC/DC circuits, components, power systems, and basic electronics for engineering students.", "Engineering", "beginner", "https://images.unsplash.com/photo-1518770660439-4636190af475?w=600&q=80", ["Electrical", "Circuits", "Electronics", "Engineering"], "The Engineering Mindset", "Engineering Educator", 5, [
        lesson("Electrical Engineering Basics", "https://www.youtube.com/watch?v=nb4ovfwW9IE", "35 min", 0, [
            q("What is Ohm's Law?", ["E=mc²", "V = I × R (Voltage = Current × Resistance)", "F = ma", "P = IV"], 1, "Ohm's Law states voltage equals current times resistance — the foundational relationship in electrical circuits."),
            q("What is the difference between AC and DC?", ["No difference", "AC alternates direction; DC flows in one constant direction", "AC is faster", "DC is wireless"], 1, "AC (alternating current) reverses direction periodically; DC (direct current) flows steadily in one direction.")])]),
    course("Mechanical Engineering Fundamentals", "Core mechanical engineering concepts. Learn statics, dynamics, thermodynamics, fluid mechanics, materials science, and manufacturing processes.", "Engineering", "beginner", "https://images.unsplash.com/photo-1537462715879-360eeb61a0ad?w=600&q=80", ["Mechanical", "Thermodynamics", "Statics", "Engineering"], "Jeff Hanson", "Mechanical Engineering Prof", 6, [
        lesson("Mechanical Engineering Crash Course", "https://www.youtube.com/watch?v=iyRkpEWx3SM", "35 min", 0, [
            q("What is Newton's First Law?", ["F=ma", "An object at rest stays at rest unless acted upon by a force", "Energy cannot be created or destroyed", "Every action has a reaction"], 1, "Newton's First Law (inertia): objects maintain their state of motion unless an external force acts on them."),
            q("What does thermodynamics study?", ["Electricity", "Heat, energy, and work — how energy transforms between forms", "Magnetism", "Light waves"], 1, "Thermodynamics studies energy transfer, particularly heat and work, and the laws governing these transformations.")])]),

    # === CONSTRUCTION ===
    course("Construction Health & Safety (OHSA)", "Essential health and safety training for construction workers. Covers hazard recognition, fall protection, scaffolding, trenching, electrical safety, and OSHA compliance.", "Construction", "beginner", "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&q=80", ["Safety", "OSHA", "Construction", "Workplace"], "Safety Pro", "Construction Safety Trainer", 4, [
        lesson("Construction Safety Full Course", "https://www.youtube.com/watch?v=Z59AnOEmkIc", "35 min", 0, [
            q("What are the 'Fatal Four' in construction?", ["Four tools", "Falls, struck-by, electrocution, and caught-in/between", "Four building types", "Four seasons"], 1, "OSHA's Fatal Four cause 60%+ of construction deaths: falls, struck-by objects, electrocution, caught-in/between."),
            q("What PPE is required on most construction sites?", ["Just gloves", "Hard hat, safety glasses, high-vis vest, steel-toe boots at minimum", "Only a hard hat", "No PPE needed"], 1, "Basic construction PPE includes hard hat, safety glasses, high-visibility vest, and steel-toe boots as minimum.")])]),
    course("Blueprint Reading for Construction", "Learn to read and interpret construction blueprints. Covers plan views, elevations, sections, symbols, dimensions, schedules, and specifications used in building projects.", "Construction", "beginner", "https://images.unsplash.com/photo-1503387762-592deb58ef4e?w=600&q=80", ["Blueprints", "Construction", "Plans", "Reading"], "Construction Fasteners", "Construction Educator", 4, [
        lesson("Blueprint Reading Full Course", "https://www.youtube.com/watch?v=ycvSzLCWq60", "30 min", 0, [
            q("What is a plan view?", ["A side view", "A bird's-eye view looking straight down at a building layout", "A 3D model", "A cross-section"], 1, "A plan view is a horizontal section looking down, showing the layout of rooms, walls, and openings on a floor."),
            q("What does a dashed line typically represent in a floor plan?", ["A wall", "Something above the cut plane (like overhead cabinets) or hidden features", "A door swing", "Plumbing"], 1, "Dashed lines indicate features above the cutting plane or hidden elements not directly visible in the view.")])]),
    course("Construction Estimating", "Learn cost estimating for construction projects. Covers quantity takeoffs, material pricing, labor costs, overhead, profit margins, and preparing professional estimates.", "Construction", "intermediate", "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=600&q=80", ["Estimating", "Construction", "Cost", "Budgeting"], "Construction Genius", "Cost Estimator", 4, [
        lesson("Construction Estimating Fundamentals", "https://www.youtube.com/watch?v=S7ByT0lC-Ks", "30 min", 0, [
            q("What is a quantity takeoff?", ["Removing materials", "Calculating the quantities of materials needed from blueprints", "A budget cut", "An inventory check"], 1, "A quantity takeoff measures and lists all materials needed for a project by analyzing drawings and specifications."),
            q("What does overhead include in an estimate?", ["Only materials", "Indirect costs like insurance, office expenses, equipment, and supervision", "Only labor", "Only profit"], 1, "Overhead covers indirect costs not tied to specific tasks — insurance, office rent, supervision, and equipment.")])]),
    course("Plumbing Basics for Beginners", "Introduction to plumbing systems. Learn pipe types, fittings, water supply, drainage, fixtures, basic repairs, and plumbing code fundamentals.", "Construction", "beginner", "https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=600&q=80", ["Plumbing", "Construction", "Pipes", "Trades"], "Roger Wakefield", "Master Plumber", 3, [
        lesson("Plumbing Basics - Complete Guide", "https://www.youtube.com/watch?v=CWhQvlAwwWA", "25 min", 0, [
            q("What are the two main plumbing systems in a building?", ["Hot and cold", "Water supply (pressure) and drainage (gravity/DWV)", "Indoor and outdoor", "Copper and PVC"], 1, "Buildings have supply systems (pressurized water in) and DWV (drain-waste-vent) systems (gravity-fed water out)."),
            q("What does a P-trap do?", ["Catches food", "Holds water to create a seal preventing sewer gases from entering", "Filters water", "Measures pressure"], 1, "The P-trap's water seal blocks sewer gases from rising through the drain into your home.")])]),
    course("HVAC Fundamentals", "Understanding heating, ventilation, and air conditioning systems. Learn refrigeration cycles, ductwork, thermostats, heat pumps, and energy efficiency principles.", "Construction", "intermediate", "https://images.unsplash.com/photo-1581094794329-c8112a89af12?w=600&q=80", ["HVAC", "Construction", "Heating", "Cooling"], "HVAC School", "HVAC Technician Trainer", 4, [
        lesson("HVAC Basics for Beginners", "https://www.youtube.com/watch?v=2GBSEaGSEZc", "30 min", 0, [
            q("What does HVAC stand for?", ["High Voltage AC", "Heating, Ventilation, and Air Conditioning", "Heavy Vehicle Auto Control", "Horizontal Vent Air Channel"], 1, "HVAC = Heating, Ventilation, and Air Conditioning — systems that control indoor climate and air quality."),
            q("How does a basic refrigeration cycle work?", ["Electricity makes cold air", "Refrigerant absorbs heat inside (evaporator) and releases it outside (condenser)", "Water freezes and melts", "Fans blow cold air"], 1, "The refrigeration cycle uses refrigerant to absorb indoor heat and release it outside through phase changes.")])]),

    # === LOGISTICS ===
    course("Warehouse Operations & Management", "Learn warehouse operations from receiving to shipping. Covers layout optimization, picking strategies, inventory systems, WMS, safety, and lean warehousing principles.", "Logistics", "beginner", "https://images.unsplash.com/photo-1553413077-190dd305871c?w=600&q=80", ["Warehouse", "Operations", "Logistics", "Inventory"], "Supply Chain Academy", "Logistics Educator", 4, [
        lesson("Warehouse Management Full Course", "https://www.youtube.com/watch?v=qqzNlPDUJGc", "30 min", 0, [
            q("What are the basic warehouse operations?", ["Only shipping", "Receiving, put-away, storage, picking, packing, and shipping", "Only storage", "Only inventory counting"], 1, "The warehouse flow: receive goods, put-away to storage, pick orders, pack them, and ship to customers."),
            q("What is a WMS?", ["A messaging system", "Warehouse Management System — software to optimize warehouse operations", "A safety protocol", "A type of forklift"], 1, "A WMS digitizes and optimizes all warehouse processes from receiving to shipping, improving accuracy and speed.")])]),
    course("Forklift Safety & Operation", "Complete forklift safety and operation training. Covers pre-operation inspection, load handling, stability, pedestrian safety, refueling, and OSHA compliance for forklift operators.", "Logistics", "beginner", "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600&q=80", ["Forklift", "Safety", "Warehouse", "Logistics"], "Safety Training", "Forklift Safety Instructor", 2, [
        lesson("Forklift Training - Complete Safety Course", "https://www.youtube.com/watch?v=WEhz6Q7FGzM", "25 min", 0, [
            q("What must be done before operating a forklift each shift?", ["Nothing special", "A pre-operation inspection checking tires, forks, fluids, and controls", "Only check fuel", "Only check the horn"], 1, "OSHA requires a pre-shift inspection covering tires, forks, mast, fluids, brakes, steering, horn, and lights."),
            q("What is the stability triangle?", ["A warning sign", "The three-point area between the front wheels and pivot that determines tip-over risk", "A type of forklift", "A load measurement"], 1, "The stability triangle is formed by the two front wheels and rear pivot — the load's center of gravity must stay within it.")])]),
    course("Supply Chain Management Fundamentals", "Understand end-to-end supply chain management. Covers procurement, manufacturing, distribution, logistics, demand planning, and supply chain optimization strategies.", "Logistics", "intermediate", "https://images.unsplash.com/photo-1494412574643-ff11b0a5eb19?w=600&q=80", ["Supply Chain", "Logistics", "Procurement", "Operations"], "CSCMP", "Supply Chain Expert", 5, [
        lesson("Supply Chain Management Full Course", "https://www.youtube.com/watch?v=Mi1QBxVjZAw", "35 min", 0, [
            q("What is supply chain management?", ["Shipping only", "Managing the flow of goods, information, and finances from supplier to customer", "Inventory counting", "Truck driving"], 1, "SCM coordinates all activities from raw materials to delivered products — procurement, production, and distribution."),
            q("What is the bullwhip effect?", ["A training method", "Demand distortion amplifying as orders move up the supply chain", "A shipping term", "A quality control issue"], 1, "The bullwhip effect causes small demand changes at retail to create increasingly larger swings upstream in the supply chain.")])]),
    course("Inventory Management & Control", "Master inventory management techniques. Learn ABC analysis, EOQ, safety stock, cycle counting, just-in-time, FIFO/LIFO, and using inventory management systems effectively.", "Logistics", "beginner", "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=600&q=80", ["Inventory", "Management", "Logistics", "Stock Control"], "AIMS Education", "Operations Manager", 3, [
        lesson("Inventory Management Full Course", "https://www.youtube.com/watch?v=Ho0rZ19Wrgo", "25 min", 0, [
            q("What is ABC analysis?", ["Alphabet sorting", "Categorizing inventory by value — A (high), B (medium), C (low) — to prioritize management", "A counting method", "A shipping code"], 1, "ABC analysis classifies items: A items (20% of items, 80% of value) get the most attention and tighter controls."),
            q("What is safety stock?", ["Backup inventory", "Extra inventory kept as a buffer against demand variability and supply delays", "Damaged goods", "Returned items"], 1, "Safety stock is buffer inventory that protects against unexpected demand spikes or supply chain disruptions.")])]),

    # === FINANCE ===
    course("Personal Finance - Money Management", "Take control of your finances. Learn budgeting, saving, debt management, credit scores, emergency funds, and building long-term financial health and independence.", "Finance", "beginner", "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&q=80", ["Personal Finance", "Budgeting", "Saving", "Money"], "The Plain Bagel", "Finance Educator", 3, [
        lesson("Personal Finance Full Course", "https://www.youtube.com/watch?v=HQzoZfc3GwQ", "30 min", 0, [
            q("What is the 50/30/20 budget rule?", ["Save 50%", "50% needs, 30% wants, 20% savings/debt repayment", "Spend 50%, save 20%", "50% housing, 30% food, 20% fun"], 1, "The 50/30/20 rule allocates after-tax income: 50% to necessities, 30% to discretionary spending, 20% to savings."),
            q("What is an emergency fund?", ["A credit card", "3-6 months of expenses saved for unexpected situations", "Insurance", "A retirement account"], 1, "An emergency fund covers 3-6 months of essential expenses, protecting you from unexpected job loss or major repairs.")])]),
    course("Stock Market Investing for Beginners", "Learn stock market fundamentals. Covers how markets work, stocks vs ETFs, fundamental analysis, technical analysis, portfolio diversification, and long-term investing strategies.", "Finance", "beginner", "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&q=80", ["Investing", "Stocks", "ETFs", "Finance"], "Patrick Boyle", "Hedge Fund Manager", 5, [
        lesson("Stock Market Full Course for Beginners", "https://www.youtube.com/watch?v=ZCFkWDdmXG8", "40 min", 0, [
            q("What is a stock?", ["A store inventory", "A share of ownership in a company", "A type of bond", "A savings account"], 1, "A stock represents partial ownership in a company — when you buy shares, you own a piece of that business."),
            q("What is an ETF?", ["A bank account", "Exchange-Traded Fund — a basket of securities that trades like a stock", "A cryptocurrency", "A savings bond"], 1, "ETFs bundle many stocks/bonds into one fund that trades on exchanges, offering instant diversification."),
            q("What is diversification?", ["Buying one stock", "Spreading investments across different assets to reduce risk", "Day trading", "Timing the market"], 1, "Diversification reduces risk by investing across different asset types, sectors, and geographies.")])]),
    course("Cryptocurrency & Blockchain Fundamentals", "Understand cryptocurrency and blockchain technology. Covers Bitcoin, Ethereum, DeFi, NFTs, wallets, exchanges, security practices, and the future of digital assets.", "Finance", "beginner", "https://images.unsplash.com/photo-1622630998477-20aa696ecb05?w=600&q=80", ["Crypto", "Blockchain", "Bitcoin", "Finance"], "Whiteboard Crypto", "Crypto Educator", 4, [
        lesson("Cryptocurrency Full Course for Beginners", "https://www.youtube.com/watch?v=VYWc9dFqROI", "35 min", 0, [
            q("What is blockchain?", ["A database", "A decentralized, immutable ledger that records transactions across many computers", "A programming language", "A bank system"], 1, "Blockchain is a distributed ledger where data is stored in blocks linked cryptographically — no central authority needed."),
            q("What is the difference between Bitcoin and Ethereum?", ["No difference", "Bitcoin is digital currency; Ethereum is a platform for smart contracts and dApps", "Bitcoin is newer", "Ethereum is a stablecoin"], 1, "Bitcoin is primarily digital money; Ethereum is a programmable blockchain platform that enables smart contracts and dApps.")])]),
    course("Financial Analysis with Excel", "Master financial analysis using Excel. Covers financial statements, ratio analysis, DCF modeling, budgeting, forecasting, pivot tables, and building financial dashboards.", "Finance", "intermediate", "https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=600&q=80", ["Excel", "Financial Analysis", "Modeling", "Finance"], "Kenji Explains", "Financial Analyst", 5, [
        lesson("Financial Analysis with Excel - Full Course", "https://www.youtube.com/watch?v=pKaRO1psCgc", "40 min", 0, [
            q("What are the three main financial statements?", ["Budget, forecast, plan", "Income Statement, Balance Sheet, Cash Flow Statement", "Revenue, expenses, profit", "Assets, liabilities, equity"], 1, "The three core statements: Income Statement (profitability), Balance Sheet (financial position), Cash Flow Statement (liquidity)."),
            q("What is a DCF model?", ["A file format", "Discounted Cash Flow — valuing a company based on projected future cash flows", "A chart type", "A tax form"], 1, "DCF estimates a company's value by projecting future cash flows and discounting them to present value.")])]),
    course("Forex Trading Fundamentals", "Introduction to foreign exchange trading. Learn currency pairs, pips, leverage, technical analysis, risk management, trading platforms, and developing a trading strategy.", "Finance", "intermediate", "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600&q=80", ["Forex", "Trading", "Currency", "Finance"], "Rayner Teo", "Forex Trader & Educator", 4, [
        lesson("Forex Trading Full Course for Beginners", "https://www.youtube.com/watch?v=Dsk15h0kFig", "35 min", 0, [
            q("What is Forex?", ["A video game", "The foreign exchange market where currencies are traded", "A stock exchange", "A bank"], 1, "Forex (FX) is the global marketplace for exchanging national currencies — the world's largest financial market."),
            q("What is a pip in Forex?", ["A seed", "The smallest price move in a currency pair, typically 0.0001", "A trading fee", "A lot size"], 1, "A pip (percentage in point) is the smallest standard price movement — for most pairs, it's the 4th decimal place.")])]),

    # === LEGAL ===
    course("Contract Law Basics", "Understand fundamental contract law. Learn elements of a contract, offer and acceptance, consideration, breach, remedies, and common contract clauses for business professionals.", "Legal", "beginner", "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&q=80", ["Contracts", "Law", "Legal", "Business"], "The Law Academy", "Legal Educator", 3, [
        lesson("Contract Law Fundamentals", "https://www.youtube.com/watch?v=2sWmAiF-a_4", "30 min", 0, [
            q("What are the essential elements of a valid contract?", ["Just a signature", "Offer, acceptance, consideration, capacity, and legality", "Only written agreement", "Just a handshake"], 1, "A valid contract requires: offer, acceptance, consideration (value exchange), legal capacity, and lawful purpose."),
            q("What is 'consideration' in contract law?", ["Being thoughtful", "Something of value exchanged between parties (money, services, goods)", "A legal opinion", "Thinking time"], 1, "Consideration is the value each party gives and receives — without it, a contract is generally unenforceable.")])]),
    course("Data Privacy & GDPR Compliance", "Navigate data privacy regulations. Learn GDPR, CCPA, data processing principles, consent management, data subject rights, breach notification, and building privacy-compliant systems.", "Legal", "intermediate", "https://images.unsplash.com/photo-1563986768609-322da13575f2?w=600&q=80", ["Privacy", "GDPR", "Compliance", "Data Protection"], "Privacy Kitchen", "Data Privacy Consultant", 4, [
        lesson("GDPR & Data Privacy Full Course", "https://www.youtube.com/watch?v=Assdm6fIHlE", "35 min", 0, [
            q("What does GDPR stand for?", ["Global Data Protection Rule", "General Data Protection Regulation", "Government Data Privacy Requirement", "General Digital Privacy Rights"], 1, "GDPR = General Data Protection Regulation — the EU's comprehensive data protection law effective since 2018."),
            q("What is the 'right to be forgotten'?", ["Memory loss", "A data subject's right to request deletion of their personal data", "Clearing browser history", "Deleting social media"], 1, "The right to erasure lets individuals request organizations delete their personal data under certain conditions.")])]),
    course("Corporate Governance & Compliance", "Understand corporate governance frameworks. Learn board responsibilities, regulatory compliance, risk management, ethics, internal controls, and corporate social responsibility.", "Legal", "intermediate", "https://images.unsplash.com/photo-1450101499163-c8848e968838?w=600&q=80", ["Governance", "Compliance", "Corporate", "Legal"], "IFC", "Governance Specialist", 3, [
        lesson("Corporate Governance Explained", "https://www.youtube.com/watch?v=4A7jK4EPJNs", "25 min", 0, [
            q("What is corporate governance?", ["Managing employees", "The system of rules and practices directing and controlling a company", "Filing taxes", "Hiring executives"], 1, "Corporate governance defines the framework of rules, relationships, and processes for directing and controlling a company."),
            q("What is the role of a board of directors?", ["Daily operations", "Overseeing management, setting strategy, and protecting shareholder interests", "Sales only", "HR management"], 1, "The board provides oversight, sets strategic direction, approves major decisions, and ensures accountability.")])]),
    course("AI Regulation & Ethics", "Understand the emerging landscape of AI regulation. Learn about the EU AI Act, responsible AI principles, bias mitigation, algorithmic accountability, and ethical AI development frameworks.", "Legal", "intermediate", "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=600&q=80", ["AI Regulation", "Ethics", "Compliance", "AI Law"], "AI Law & Policy", "AI Ethics Researcher", 3, [
        lesson("AI Regulation and Ethics", "https://www.youtube.com/watch?v=aGWfJGihIYQ", "30 min", 0, [
            q("What is the EU AI Act?", ["A movie", "The world's first comprehensive legal framework regulating artificial intelligence", "A chatbot", "An AI model"], 1, "The EU AI Act is landmark legislation classifying AI systems by risk level and imposing requirements accordingly."),
            q("What is algorithmic bias?", ["A coding error", "Systematic unfairness in AI outputs due to biased training data or design", "A feature, not a bug", "Slow processing"], 1, "Algorithmic bias occurs when AI systems produce unfair outcomes due to biased data, design choices, or assumptions.")])]),
    course("Cyber Law & Digital Regulations", "Navigate the legal landscape of the digital world. Covers cybercrime laws, intellectual property online, e-commerce regulations, social media law, and digital evidence.", "Legal", "beginner", "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=600&q=80", ["Cyber Law", "Digital", "Regulations", "Legal"], "Internet Law Center", "Cyber Law Professor", 3, [
        lesson("Cyber Law Full Course", "https://www.youtube.com/watch?v=HApC5eSPajM", "30 min", 0, [
            q("What is cybercrime?", ["Using computers", "Criminal activities carried out using computers or the internet", "Online shopping", "Social media use"], 1, "Cybercrime includes hacking, identity theft, phishing, ransomware, and any illegal activity using digital technology."),
            q("What is intellectual property in the digital context?", ["Physical property", "Creations of the mind (software, content, designs) protected by law online", "Domain names only", "Hardware"], 1, "Digital IP includes copyrighted content, software code, trademarks, and patents — all protected under law.")])]),
]

for c in COURSES:
    r = requests.post(f"{API_URL}/api/academy/admin/courses", headers=H, json=c)
    status = "OK" if r.status_code == 200 else "FAIL"
    print(f"  [{status}] {c['category']:18} | {c['title'][:45]}")
print(f"\nDone! Seeded {len(COURSES)} courses.")
